### PR TITLE
New polar stereographic interpolation for hemi-cmaq (Type 6).

### PR DESCRIPTION
**Pull request by drnimbusrain**
@ytangnoaa Can you help look at what I have done here in this draft PR for polar stereographic interpolation and hemi-cmaq?  

I have added a new routine xy2ll_ps.f90, which transforms the XY map coordinates to lat/lon data for a polar stereographic system.  I add now the option type 6 in rdfv3.f90 to allow for user option to interpolate the GFSv16 data to polar stereographic, and have tested against what Barron provided for their Hemi-CMAQ domain.  I also adopt the already present mapfac_ps routines for polar stereographic in MCIP.  

It seems to work OK mostly, and my interpolated gridcro2d output grid matches exactly what Barron provided for Hemi-CMAQ:

**Latitude:**
image
**Longitude:**
image
**MapFac**
image
**LWMASK**
image
**DLUSE:**
image

The only issue it seems,  is at the grid point exactly at the pole of 90 degrees, where the interpolation leads to a single missing value for some interpolated variables, e.g., 
**Terrain Height:**
image
**Terrain Height (scale change):**
image

This occurs across many of the variables after interpolation, but not all, e.g., metcro3d variables below:
**Temperature (OK):**
image
**Water Vapor (OK):**
image
**Pressure (erroneous value at the pole grid cell):**
image

Also, while the JACOBM seems OK,
image

The JACOBF are all missing,
image

Finally, there is clearly some issues with the 3D dot wind fields, VWIND:
image

### CODE REVIEW

**Comment by drnimbusrain** [comment]
@ytangnoaa  Also, when compiling/running in debug, I do notice an error with this at:

At line 52 of file getxyindex.f90
Fortran runtime error: Index '3073' of dimension 1 of array 'tlon' above upper bound of 3072

Error termination. Backtrace:
At line 52 of file getxyindex.f90
Fortran runtime error: Index '3073' of dimension 1 of array 'tlon' above upper bound of 3072

**Comment by drnimbusrain** [comment]
I have also added some code to fix longitudes, but this is not related to the debug error above.

Barron's Hemi-CMAQ Longitude:
image

**Our Interpolated NACC Longitude:**
image

Seems the 3D Dot wind files are a bit better with this:
image

**Comment by ytangnoaa** [comment]
Patrick. Thank you for your effort. It looks great. You may create some sample files to Barron with his 44 vertical layers up to 50hPa.

**Comment by drnimbusrain** [comment]
@ytangnoaa Thanks.

However, there still seems to be some issue at the pole though still, and it may cause the following debug error:

At line 52 of file getxyindex.f90
Fortran runtime error: Index '3073' of dimension 1 of array 'tlon' above upper bound of 3072

Error termination. Backtrace:
At line 52 of file getxyindex.f90
Fortran runtime error: Index '3073' of dimension 1 of array 'tlon' above upper bound of 3072

**Comment by ytangnoaa** [comment]
> @ytangnoaa Thanks.
> 
> However, there still seems to be some issue at the pole though still, and it may cause the following debug error:
> 
> At line 52 of file getxyindex.f90 Fortran runtime error: Index '3073' of dimension 1 of array 'tlon' above upper bound of 3072
> 
> Error termination. Backtrace: At line 52 of file getxyindex.f90 Fortran runtime error: Index '3073' of dimension 1 of array 'tlon' above upper bound of 3072

I offline tested the IOAPI routine for xy2ll_ps

aaqest:/data/aqf/youhuat/map/prog/xyll-hcmaq-108.ioapi.f90

xyll-hcmaq-108.ioapi.x 1.0 1.0
-143.0000      -15.12766

It is quite consistent with the GRIDCRO2D file in
aaqest:/data/aqf6/youhuat/HEMIS-CMAQ/GRIDCRO2D.108NHEMI2.44L.160115.nc4

**Comment by drnimbusrain** [comment]
@ytangnoaa Yes, I also tested my xy2ll_ps routine, and it is working properly.  I think there is another issue with how the polar sterographic works in the getxyindex and the size of longitude array.

**Comment by ytangnoaa** [comment]
> @ytangnoaa Yes, I also tested my xy2ll_ps routine, and it is working properly. I think there is another issue with how the polar sterographic works in the getxyindex and the size of longitude array.

Could you print out the lat/lon information when dimension > 3072

**Comment by drnimbusrain** [comment]
@ytangnoaa It seems that the getxyindex for longitude can reach i = 3072 and not find an index (likely at pole), and thus the code goes out of bound in the polar stereographic case with tlon(i+1):

if(xlontmp.lt.0) xlontmp=xlontmp+360
  do i=1,ix
   if(xlontmp.ge.tlon(i).and.xlontmp.le.**tlon(i+1)**) then
    xi=i+(xlontmp-tlon(i))/(**tlon(i+1)**-tlon(i))
    exit
   endif
  enddo

This does not happen in the LCC case, so we never see an error.   Thus, we may need to modify getxyindex slightly to account for this possibility in polar stereographic.

**Comment by ytangnoaa** [comment]
> @ytangnoaa It seems that the getxyindex for longitude can reach i = 3072 and not find an index (likely at pole), and thus the code goes out of bound in the polar stereographic case with tlon(i+1):
> 
> if(xlontmp.lt.0) xlontmp=xlontmp+360 do i=1,ix if(xlontmp.ge.tlon(i).and.xlontmp.le.**tlon(i+1)**) then xi=i+(xlontmp-tlon(i))/(**tlon(i+1)**-tlon(i)) exit endif enddo
> 
> This does not happen in the LCC case, so we never see an error. Thus, we may need to modify getxyindex slightly to account for this possibility in polar stereographic.

Thank you for your effort. I see the issue

**Comment by ytangnoaa** [comment]
> > @ytangnoaa It seems that the getxyindex for longitude can reach i = 3072 and not find an index (likely at pole), and thus the code goes out of bound in the polar stereographic case with tlon(i+1):
> > if(xlontmp.lt.0) xlontmp=xlontmp+360 do i=1,ix if(xlontmp.ge.tlon(i).and.xlontmp.le.**tlon(i+1)**) then xi=i+(xlontmp-tlon(i))/(**tlon(i+1)**-tlon(i)) exit endif enddo
> > This does not happen in the LCC case, so we never see an error. Thus, we may need to modify getxyindex slightly to account for this possibility in polar stereographic.
> 
> Thank you for your effort. I see the issue

I created a branch "feature/hemi-cmaq2" for the fix. Please try and let me know the issue

**Comment by drnimbusrain** [comment]
@ytangnoaa Thank you for your changes.  I tested your branch with debug as before, but it fails as:

**At line 113 of file myinterp.f90
Fortran runtime error: Index '0' of dimension 1 of array 'ain' below lower bound of 1**

Error termination. Backtrace:
#0  0x5703fc in myinterp_
        at /groups/ESS3/pcampbe8/NACC-test-hemi-cmaq2/parallel/src/myinterp.f90:113
#1  0x66cee6 in rdfv3_
        at /groups/ESS3/pcampbe8/NACC-test-hemi-cmaq2/parallel/src/rdfv3.f90:1108
#2  0x4a2c37 in getmet_
        at /groups/ESS3/pcampbe8/NACC-test-hemi-cmaq2/parallel/src/getmet.f90:74
#3  0x4048c5 in mcip
        at /groups/ESS3/pcampbe8/NACC-test-hemi-cmaq2/parallel/src/mcip.f90:186
#4  0x404b71 in main
        at /groups/ESS3/pcampbe8/NACC-test-hemi-cmaq2/parallel/src/mcip.f90:83



See your changes:  https://github.com/noaa-oar-arl/NACC/compare/feature/hemi-cmaq...feature/hemi-cmaq2#diff-34770fe0aa98082c2ce11ae7e9ee9467bf405c5eb52649c4883ae7cd6bd048b1R113

**Comment by drnimbusrain** [comment]
@ytangnoaa Also the log files for your new branch show the following:

wrong xlontmp    217.000000       359.882812       0.00000000
 wrong xlontmp    217.304764       359.882812       0.00000000
 wrong xlontmp    217.612762       359.882812       0.00000000
 wrong xlontmp    217.924042       359.882812       0.00000000
 wrong xlontmp    218.238632       359.882812       0.00000000
 wrong xlontmp    218.556564       359.882812       0.00000000
 wrong xlontmp    218.877884       359.882812       0.00000000
...
...

**Comment by drnimbusrain** [comment]
@ytangnoaa It seems in your changes in this branch are leading to xindices that are all zero from your getxyindex changes:

xdindex =    0.00000000       0.00000000       0.00000000       0.00000000       0.00000000 ....

Seems like your new yindices may be OK in your new branch:  ydindex =    907.490295       904.989136       902.484497 ...

**Comment by drnimbusrain** [comment]
@ytangnoaa Judging by what is happening above,it seems you may have a typo in your changed getxyindex code:

 else if (xlontmp.ge.tlon(ix)) then

should be

 else if (xlontmp.le.tlon(ix)) then

See latest [commit](https://github.com/noaa-oar-arl/NACC/commit/bd5d2d33d92492b520a07ba81c8fc92959e2b551) in your new branch, and confirm.

**Comment by drnimbusrain** [comment]
@ytangnoaa Well, that change in my [commit](https://github.com/noaa-oar-arl/NACC/commit/bd5d2d33d92492b520a07ba81c8fc92959e2b551) leads to another error in your branch:

before getmet           0
 wrong index    1852.73328       907.490295

     *** ERROR ABORT in subroutine MYINTERP
     ABNORMAL TERMINATION IN MYINTERP
     Date and time  12:00:00  Jan. 12, 2020   (2020012:120000)

 wrong index    1852.73328       907.490295

     *** ERROR ABORT in subroutine MYINTERP
     ABNORMAL TERMINATION IN MYINTERP
     Date and time  12:00:00  Jan. 12, 2020   (2020012:120000)

Seems like the indices are working, but there is an error with myinterp with checking...

**Comment by ytangnoaa** [comment]
> @ytangnoaa Judging by what is happening above,it seems you may have a typo in your changed getxyindex code:
> 
> else if (xlontmp.ge.tlon(ix)) then
> 
> should be
> 
> else if (xlontmp.le.tlon(ix)) then
> 
> See latest [commit](https://github.com/noaa-oar-arl/NACC/commit/bd5d2d33d92492b520a07ba81c8fc92959e2b551) in your new branch, and confirm.

Yes, it should be "le"

**Comment by drnimbusrain** [comment]
@ytangnoaa OK, then that fixes your getxyindex changes and the indices look good, but there is still an error with your new myinterp, which suggests the error is here:

    if(x(i,j).gt.iout.and.x(i,j).le.iout+1) then
...
else if(x(i,j).le.iout) then
...
else
       print*,'wrong index ',x(i,j),y(i,j)

iout is always much lower than the indice x(i,j), so it always says wrong index...

before getmet           0
 wrong index    1852.73328       907.490295             iout=190         jout=190

Seems like you may be comparing the wrong things in the new conditions statements.

**Comment by ytangnoaa** [comment]
> @ytangnoaa OK, then that fixes your getxyindex changes and the indices look good, but there is still an error with your new myinterp, which suggests the error is here:
> 
> ```
> if(x(i,j).gt.iout.and.x(i,j).le.iout+1) then
> ```
> 
> ... else if(x(i,j).le.iout) then ... else print*,'wrong index ',x(i,j),y(i,j)
> 
> iout is always much lower than the indice x(i,j), so it always says wrong index...
> 
> before getmet 0 wrong index 1852.73328 907.490295 iout=190 jout=190
> 
> Seems like you may be comparing the wrong things in the new conditions statements.


could you test the updated file in feature/hemi-cmaq2 branch "myinterp.f90"

**Comment by drnimbusrain** [comment]
@ytangnoaa  Sure, I will test it today.

**Comment by drnimbusrain** [comment]
@ytangnoaa This looks like it works better now!  I am going to merge your feature/hemi-cmaq2 into mine feature/hemi-cmaq

**Pull request merged**
